spring.application.name=smart-assist-mcp-client
server.port=8081
server.servlet.context-path=/mcp-client
spring.ai.openai.api-key=${OPEN_AI_API_KEY}

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

#Logging
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

logging.level.root=INFO
logging.level.com.inchbyinch=DEBUG
logging.level.org.springframework.ai=DEBUG
spring.devtools.add-properties = false
